// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    facility_detail: {
        name: "facility_detail";
        parameters: {
          /** STRING - use sql.string() */
          facility_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          facility_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          organization_type: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          district: string;
          /** @sqlType STRING */
          state: string;
          /** @sqlType STRING */
          address_line1: string;
          /** @sqlType STRING */
          address_line2: string;
          /** @sqlType STRING */
          postcode_raw: string;
          /** @sqlType STRING */
          phone: string;
          /** @sqlType STRING */
          email: string;
          /** @sqlType STRING */
          website: string;
          /** @sqlType INT */
          number_doctors: number;
          /** @sqlType INT */
          capacity: number;
          /** @sqlType INT */
          year_established: number;
          /** @sqlType STRING */
          specialties: string;
          /** @sqlType INT */
          n_specialties: number;
          /** @sqlType INT */
          n_distinct_sources: number;
          /** @sqlType STRING */
          description: string;
          /** @sqlType STRING */
          source_urls: string;
          /** @sqlType STRING */
          page_update_date: string;
          /** @sqlType DOUBLE */
          latitude: number;
          /** @sqlType DOUBLE */
          longitude: number;
          /** @sqlType DECIMAL(17,0) */
          trust_score: number;
          /** @sqlType STRING */
          trust_tier: string;
          /** @sqlType INT */
          corroboration_score: number;
          /** @sqlType DECIMAL(14,0) */
          completeness_score: number;
          /** @sqlType INT */
          consistency_score: number;
          /** @sqlType INT */
          recency_score: number;
          /** @sqlType STRING */
          trust_flags: string;
        }>;
      };
    nfhs_context: {
        name: "nfhs_context";
        parameters: {
          /** STRING - use sql.string() */
          district: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          district_name: string;
          /** @sqlType STRING */
          state_ut: string;
          /** @sqlType DOUBLE */
          institutional_birth_5y_pct: number;
          /** @sqlType DOUBLE */
          births_attended_by_skilled_hp_5y_10_pct: number;
          /** @sqlType DOUBLE */
          all_w15_49_who_are_anaemic_pct: number;
          /** @sqlType DOUBLE */
          hh_improved_water_pct: number;
          /** @sqlType DOUBLE */
          hh_use_improved_sanitation_pct: number;
          /** @sqlType DOUBLE */
          hh_member_covered_health_insurance_pct: number;
          /** @sqlType DOUBLE */
          women_age_15_49_who_are_literate_pct: number;
        }>;
      };
    pincode_info: {
        name: "pincode_info";
        parameters: {
          /** BIGINT - use sql.bigint() */
          pincode: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          pincode: number;
          /** @sqlType STRING */
          district: string;
          /** @sqlType STRING */
          state: string;
          /** @sqlType DOUBLE */
          latitude: number;
          /** @sqlType DOUBLE */
          longitude: number;
        }>;
      };
    recommend: {
        name: "recommend";
        parameters: {
          /** STRING - use sql.string() */
          specialty: SQLStringMarker;
          /** BIGINT - use sql.bigint() */
          pincode: SQLNumberMarker;
          /** DOUBLE - use sql.double() */
          radius_km: SQLNumberMarker;
          /** DOUBLE - use sql.double() */
          trust_weight: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          facility_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          district: string;
          /** @sqlType STRING */
          state: string;
          /** @sqlType STRING */
          matched_specialties: string;
          /** @sqlType INT */
          number_doctors: number;
          /** @sqlType INT */
          capacity: number;
          /** @sqlType DOUBLE */
          distance_km: number;
          /** @sqlType DOUBLE */
          proximity_score: number;
          /** @sqlType INT */
          trust_score: number;
          /** @sqlType STRING */
          trust_tier: string;
          /** @sqlType STRING */
          trust_flags: string;
          /** @sqlType DOUBLE */
          rank_score: number;
        }>;
      };
    specialties: {
        name: "specialties";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          specialty: string;
          /** @sqlType BIGINT */
          n_facilities: number;
        }>;
      };
    trust_overview: {
        name: "trust_overview";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          trust_tier: string;
          /** @sqlType BIGINT */
          n_facilities: number;
          /** @sqlType DECIMAL(19,1) */
          avg_score: number;
        }>;
      };
  }
}
